version: '3'

networks:
  phalcon_phalcon_my_network:
    driver: bridge

services:
  nginx:
    image: my-nginx-image
    restart: always
    ports:
      - "8086:80"
    build:
        context: .
        dockerfile: docker/DockerfileNginx
#    volumes:
#      - /etc/nginx/sites-enabled/default:/etc/nginx/conf.d/default.conf
#      - . :/usr/share/nginx/html

    networks:
      - phalcon_phalcon_my_network
    depends_on:
      - php-fpm


  php-fpm:
#    proveri da li je expose-ovan defaultni port 9000
    image: my-image
    environment:
      DB_HOST: mysql
    ports:
      - "9000:9000" # Expose port 9000
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/Phalcon
    networks:
      - phalcon_phalcon_my_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.34-debian
#    proveri mapiranje portova
    environment:
      MYSQL_ROOT_PASSWORD: Sifra123!
      MYSQL_DATABASE: phalcon_database
      MYSQL_USER: katarinakat
      MYSQL_PASSWORD: Sifra123!
    ports:
     - "3306:3306"  # Map container port 3306 to host port 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - phalcon_phalcon_my_network


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: mysql
    networks:
      - phalcon_phalcon_my_network

volumes:
    mysql: