<?php
use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;

$form = new Form();

$form->add(
    new Text(
        'name',
        [
            'maxlength'   => 30,
            'placeholder' => 'First Name',
        ]
    ),
);
$form->add(
    new Text(
        'email',
        [
            'maxlength'   => 30,
            'placeholder' => 'Email',
        ]
    ),
);
$form->add(
    new Text(
        'password',
        [
            'maxlength'   => 30,
            'placeholder' => 'Password',
        ]
    ),
);
?>
<h2>Sign up using this form test</h2>
<form method='post'>
    <p>
        <label for="name">Name</label>
        <?php echo $form->render('name'); ?>
    </p>
    <p>
        <label for="name">Email</label>
        <?php echo $form->render('email'); ?>
    </p>
    <p>
        <label for="name">Password</label>
        <?php echo $form->render('password'); ?>
    </p>
    <p>
        <input type='submit' value='Save' formaction="signup/register"/>
    </p>
</form>



<?php //echo $this->tag->form("signup/register"); ?>
<!---->
<!--<p>-->
<!--    <label for="name">Name</label>-->
<!--    --><?php //echo $this->tag->inputText("name") ?>
<!--</p>-->
<!---->
<!--<p>-->
<!--    <label for="email">E-Mail</label>-->
<!--    --><?php //echo $this->tag->inputText("email"); ?>
<!--</p>-->
<!---->
<!--<p>-->
<!--    --><?php //echo $this->tag->inputSubmit("Register"); ?>
<!--</p>-->
<!---->
<?php //echo $this->tag->close('form'); ?>

