<?php
use Phalcon\Forms\Form;
use Phalcon\Forms\Element\Text;


$form = new Form();

$form->add(
    new Text(
        'name',
        [
            'maxlength'   => 30,
            'placeholder' => 'First Name',
        ]
    ),
);
$form->add(
    new Text(
        'email',
        [
            'maxlength'   => 30,
            'placeholder' => 'Email',
        ]
    ),
);
$form->add(
    new Text(
        'password',
        [
            'maxlength'   => 30,
            'placeholder' => 'name',
        ]
    ),
);
?>
<h2>Edit this form test</h2>
<form method='post'>
    <p>
        <label for="name">Name</label>
        <?php echo $form->render('name'); ?>
    </p>
    <p>
        <label for="name">Email</label>
        <?php echo $form->render('email'); ?>
    </p>
    <p>
        <label for="name">Password</label>
        <?php echo $form->render('password'); ?>
    </p>
    <p>
        <input type='submit' value='Save' formaction="signup/register"/>
    </p>
</form>